### ISSUE TITLE
custom triton build

### ISSUE THREAD

**Issue by chain2k** [lshqqytiger/triton#1]
Hi, I have successfully built a custom triton, but I always get an error when I check ‘import triton’:
`ImportError: DLL load failed while importing libtriton:`
Assembled as per instructions, did checkout LLVM 1cec5fffd8fddd9d85b516f876093b0e3f0eec5f as in llvm-hash.txt
But after building triton in **build\cmake.win-amd64-cpython-3.10\** there is no **triton.dll**, there is **libtriton.pyd**. I copied it to ‘triton\_C\libtriton.pyd’.
Installed Triton with develop, but when checking - the library is not found. I copied it manually. The situation does not change. 
Tried to build a wheel and install from it into venv, same error. Tried to build a wheel, where I added in setup.py in package_data:
```
package_data = {
    ‘triton/tools/extra": sum((b.tools_package_data for b in backends), []),
    **{f ‘triton/backends/{b.name}’: b.package_data for b in backends},
    ‘triton/language/extra": sum((b.language_package_data for b in backends), []),
    ‘triton/_C": [‘libtriton.pyd’], # <-- add this one
}
```
The wheel installation copied the library, but the error remains....
I don't know what else to try
I can describe step by step how I build llvm and triton
If it becomes clear where I am wrong and I successfully unbuild and install custom triton, I will make detailed instructions so that others do not repeat my mistakes.

**Comment by lshqqytiger** [comment]
There're compiled wheels in the releases tab.
https://github.com/lshqqytiger/triton/releases/tag/bb314b47
Do you want to build triton from source?

**Comment by chain2k** [comment]
Yes< I want to build from source, because with [https://github.com/lshqqytiger/triton/releases/download/bb314b47/triton-3.3.0+gitbb314b47-cp310-cp310-win_amd64.whl](url) framepack doesn't work, import error. And this is the main package for which I wanted to install Triton

**Comment by LuXuxue** [comment]
When I use TorchCompileModel with bb314b47 in ComfyUI, Error Report is list below. I have no idea about how to fix it. 2b248f14 can work but have no speed-up.

# ComfyUI Error Report
## Error Details
- **Node ID:** 9
- **Node Type:** TorchCompileModel
- **Exception Type:** ImportError
- **Exception Message:** cannot import name 'AttrsDescriptor' from 'triton.compiler.compiler' (C:\Portable\torch260\Lib\site-packages\triton\compiler\compiler.py)
## Stack Trace
```
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Portable\ComfyUI-Zluda\execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Portable\ComfyUI-Zluda\execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Portable\ComfyUI-Zluda\execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Portable\ComfyUI-Zluda\comfy_extras\nodes_torch_compile.py", line 17, in patch
    m.add_object_patch("diffusion_model", torch.compile(model=m.get_model_object("diffusion_model"), backend=backend))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Portable\torch260\Lib\site-packages\torch\__init__.py", line 2565, in compile
    return torch._dynamo.optimize(
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 842, in optimize
    return _optimize(rebuild_ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 896, in _optimize
    backend = get_compiler_fn(backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 783, in get_compiler_fn
    from .repro.after_dynamo import wrap_backend_debug

  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 16, in <module>
    from torch._dynamo.debug_utils import (

  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\debug_utils.py", line 25, in <module>
    from torch._dynamo.testing import rand_strided

  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\testing.py", line 27, in <module>
    from torch._dynamo.backends.debugging import aot_eager

  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\backends\debugging.py", line 10, in <module>
    from functorch.compile import min_cut_rematerialization_partition

  File "C:\Portable\torch260\Lib\site-packages\functorch\compile\__init__.py", line 2, in <module>
    from torch._functorch.aot_autograd import (

  File "C:\Portable\torch260\Lib\site-packages\torch\_functorch\aot_autograd.py", line 36, in <module>
    from torch._inductor.output_code import OutputCode

  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\output_code.py", line 47, in <module>
    from torch._inductor.cudagraph_utils import (

  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\cudagraph_utils.py", line 10, in <module>
    from torch._inductor.utils import InputType

  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\utils.py", line 50, in <module>
    from torch._inductor.runtime.hints import DeviceProperties

  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\runtime\hints.py", line 67, in <module>
    from triton.compiler.compiler import AttrsDescriptor

```
## System Information
- **ComfyUI Version:** 0.3.29
- **Arguments:** ComfyUI-Zluda\main.py --fp8_e5m2-unet --fast --listen --output-directory D:\ComfyUI
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.6.0+cu118
## Devices

- **Name:** cuda:0 AMD Radeon 780M Graphics [ZLUDA] : native
  - **Type:** cuda
  - **VRAM Total:** 36431233024
  - **VRAM Free:** 34172175360
  - **Torch VRAM Total:** 1793064960
  - **Torch VRAM Free:** 140059648

## Logs
```
2025-04-23T13:44:03.309924 - Setting output directory to: D:\ComfyUI
2025-04-23T13:44:04.826025 - Checkpoint files will always be loaded safely.
2025-04-23T13:44:04.843798 - Installed version of comfyui-frontend-package: 1.16.92025-04-23T13:44:04.843798 - 
2025-04-23T13:44:04.855135 - Installed version of comfyui-workflow-templates: 0.1.32025-04-23T13:44:04.855135 - 
2025-04-23T13:44:09.949903 -   ::  ONNX Runtime not installed — skipping patch.2025-04-23T13:44:09.949903 - 
2025-04-23T13:44:09.949903 -   ::  ZLUDA detected, disabling non-supported functions.      2025-04-23T13:44:09.949903 - 
2025-04-23T13:44:09.958597 -   ::  CuDNN, flash_sdp, mem_efficient_sdp disabled.           2025-04-23T13:44:09.958597 - 
2025-04-23T13:44:09.958597 -   ::  Using ZLUDA with device: AMD Radeon 780M Graphics [ZLUDA]2025-04-23T13:44:09.958597 - 
2025-04-23T13:44:09.958597 - ***--------------------------------------------------------***
2025-04-23T13:44:09.958597 - 
2025-04-23T13:44:10.408268 - Total VRAM 34744 MB, total RAM 48959 MB
2025-04-23T13:44:10.408268 - pytorch version: 2.6.0+cu118
2025-04-23T13:44:10.408268 - Set vram state to: NORMAL_VRAM
2025-04-23T13:44:10.408268 - Device: cuda:0 AMD Radeon 780M Graphics [ZLUDA] : native
2025-04-23T13:44:10.768377 - Using pytorch attention
2025-04-23T13:44:12.572726 - Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
2025-04-23T13:44:12.572726 - ComfyUI version: 0.3.29
2025-04-23T13:44:12.606282 - ComfyUI frontend version: 1.16.9
2025-04-23T13:44:12.606282 - [Prompt Server] web root: C:\Portable\torch260\Lib\site-packages\comfyui_frontend_package\static
2025-04-23T13:44:13.091308 - 
Import times for custom nodes:
2025-04-23T13:44:13.091308 -    0.0 seconds: C:\Portable\ComfyUI-Zluda\custom_nodes\websocket_image_save.py
2025-04-23T13:44:13.091308 -    0.0 seconds: C:\Portable\ComfyUI-Zluda\custom_nodes\ComfyUI-Custom-Scripts
2025-04-23T13:44:13.091308 - 
2025-04-23T13:44:13.101310 - Starting server

2025-04-23T13:44:13.101310 - To see the GUI go to: http://0.0.0.0:8188
2025-04-23T13:44:13.101310 - To see the GUI go to: http://[::]:8188
2025-04-23T13:44:29.366664 - got prompt
2025-04-23T13:44:29.493300 - model weight dtype torch.float8_e5m2, manual cast: torch.float16
2025-04-23T13:44:29.509007 - model_type EPS
2025-04-23T13:44:30.638217 - Using pytorch attention in VAE
2025-04-23T13:44:30.639137 - Using pytorch attention in VAE
2025-04-23T13:44:30.690058 - VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
2025-04-23T13:44:31.037527 - Requested to load SDXLClipModel
2025-04-23T13:44:31.053251 - loaded completely 9.5367431640625e+25 1560.802734375 True
2025-04-23T13:44:31.068909 - CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
2025-04-23T13:44:32.565462 - Requested to load SDXLClipModel
2025-04-23T13:44:34.125165 - !!! Exception during processing !!! cannot import name 'AttrsDescriptor' from 'triton.compiler.compiler' (C:\Portable\torch260\Lib\site-packages\triton\compiler\compiler.py)
2025-04-23T13:44:34.211033 - Traceback (most recent call last):
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\runtime\hints.py", line 46, in <module>
    from triton.backends.compiler import AttrsDescriptor
ImportError: cannot import name 'AttrsDescriptor' from 'triton.backends.compiler' (C:\Portable\torch260\Lib\site-packages\triton\backends\compiler.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\ComfyUI-Zluda\comfy_extras\nodes_torch_compile.py", line 17, in patch
    m.add_object_patch("diffusion_model", torch.compile(model=m.get_model_object("diffusion_model"), backend=backend))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\__init__.py", line 2565, in compile
    return torch._dynamo.optimize(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 842, in optimize
    return _optimize(rebuild_ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 896, in _optimize
    backend = get_compiler_fn(backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 783, in get_compiler_fn
    from .repro.after_dynamo import wrap_backend_debug
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 16, in <module>
    from torch._dynamo.debug_utils import (
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\debug_utils.py", line 25, in <module>
    from torch._dynamo.testing import rand_strided
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\testing.py", line 27, in <module>
    from torch._dynamo.backends.debugging import aot_eager
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\backends\debugging.py", line 10, in <module>
    from functorch.compile import min_cut_rematerialization_partition
  File "C:\Portable\torch260\Lib\site-packages\functorch\compile\__init__.py", line 2, in <module>
    from torch._functorch.aot_autograd import (
  File "C:\Portable\torch260\Lib\site-packages\torch\_functorch\aot_autograd.py", line 36, in <module>
    from torch._inductor.output_code import OutputCode
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\output_code.py", line 47, in <module>
    from torch._inductor.cudagraph_utils import (
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\cudagraph_utils.py", line 10, in <module>
    from torch._inductor.utils import InputType
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\utils.py", line 50, in <module>
    from torch._inductor.runtime.hints import DeviceProperties
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\runtime\hints.py", line 67, in <module>
    from triton.compiler.compiler import AttrsDescriptor
ImportError: cannot import name 'AttrsDescriptor' from 'triton.compiler.compiler' (C:\Portable\torch260\Lib\site-packages\triton\compiler\compiler.py)

2025-04-23T13:44:34.211033 - Prompt executed in 4.84 seconds
2025-04-23T13:49:10.698403 - got prompt
2025-04-23T13:49:10.723299 - !!! Exception during processing !!! cannot import name 'AttrsDescriptor' from 'triton.compiler.compiler' (C:\Portable\torch260\Lib\site-packages\triton\compiler\compiler.py)
2025-04-23T13:49:10.723299 - Traceback (most recent call last):
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\runtime\hints.py", line 46, in <module>
    from triton.backends.compiler import AttrsDescriptor
ImportError: cannot import name 'AttrsDescriptor' from 'triton.backends.compiler' (C:\Portable\torch260\Lib\site-packages\triton\backends\compiler.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\ComfyUI-Zluda\comfy_extras\nodes_torch_compile.py", line 17, in patch
    m.add_object_patch("diffusion_model", torch.compile(model=m.get_model_object("diffusion_model"), backend=backend))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\__init__.py", line 2565, in compile
    return torch._dynamo.optimize(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 842, in optimize
    return _optimize(rebuild_ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 896, in _optimize
    backend = get_compiler_fn(backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 783, in get_compiler_fn
    from .repro.after_dynamo import wrap_backend_debug
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 16, in <module>
    from torch._dynamo.debug_utils import (
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\debug_utils.py", line 25, in <module>
    from torch._dynamo.testing import rand_strided
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\testing.py", line 27, in <module>
    from torch._dynamo.backends.debugging import aot_eager
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\backends\debugging.py", line 10, in <module>
    from functorch.compile import min_cut_rematerialization_partition
  File "C:\Portable\torch260\Lib\site-packages\functorch\compile\__init__.py", line 2, in <module>
    from torch._functorch.aot_autograd import (
  File "C:\Portable\torch260\Lib\site-packages\torch\_functorch\aot_autograd.py", line 36, in <module>
    from torch._inductor.output_code import OutputCode
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\output_code.py", line 47, in <module>
    from torch._inductor.cudagraph_utils import (
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\cudagraph_utils.py", line 10, in <module>
    from torch._inductor.utils import InputType
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\utils.py", line 50, in <module>
    from torch._inductor.runtime.hints import DeviceProperties
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\runtime\hints.py", line 67, in <module>
    from triton.compiler.compiler import AttrsDescriptor
ImportError: cannot import name 'AttrsDescriptor' from 'triton.compiler.compiler' (C:\Portable\torch260\Lib\site-packages\triton\compiler\compiler.py)

2025-04-23T13:49:10.723299 - Prompt executed in 0.03 seconds
2025-04-23T13:52:01.981841 - got prompt
2025-04-23T13:52:02.278571 - !!! Exception during processing !!! cannot import name 'AttrsDescriptor' from 'triton.compiler.compiler' (C:\Portable\torch260\Lib\site-packages\triton\compiler\compiler.py)
2025-04-23T13:52:02.278571 - Traceback (most recent call last):
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\runtime\hints.py", line 46, in <module>
    from triton.backends.compiler import AttrsDescriptor
ImportError: cannot import name 'AttrsDescriptor' from 'triton.backends.compiler' (C:\Portable\torch260\Lib\site-packages\triton\backends\compiler.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Portable\ComfyUI-Zluda\execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\ComfyUI-Zluda\comfy_extras\nodes_torch_compile.py", line 17, in patch
    m.add_object_patch("diffusion_model", torch.compile(model=m.get_model_object("diffusion_model"), backend=backend))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\__init__.py", line 2565, in compile
    return torch._dynamo.optimize(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 842, in optimize
    return _optimize(rebuild_ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 896, in _optimize
    backend = get_compiler_fn(backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\eval_frame.py", line 783, in get_compiler_fn
    from .repro.after_dynamo import wrap_backend_debug
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 16, in <module>
    from torch._dynamo.debug_utils import (
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\debug_utils.py", line 25, in <module>
    from torch._dynamo.testing import rand_strided
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\testing.py", line 27, in <module>
    from torch._dynamo.backends.debugging import aot_eager
  File "C:\Portable\torch260\Lib\site-packages\torch\_dynamo\backends\debugging.py", line 10, in <module>
    from functorch.compile import min_cut_rematerialization_partition
  File "C:\Portable\torch260\Lib\site-packages\functorch\compile\__init__.py", line 2, in <module>
    from torch._functorch.aot_autograd import (
  File "C:\Portable\torch260\Lib\site-packages\torch\_functorch\aot_autograd.py", line 36, in <module>
    from torch._inductor.output_code import OutputCode
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\output_code.py", line 47, in <module>
    from torch._inductor.cudagraph_utils import (
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\cudagraph_utils.py", line 10, in <module>
    from torch._inductor.utils import InputType
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\utils.py", line 50, in <module>
    from torch._inductor.runtime.hints import DeviceProperties
  File "C:\Portable\torch260\Lib\site-packages\torch\_inductor\runtime\hints.py", line 67, in <module>
    from triton.compiler.compiler import AttrsDescriptor
ImportError: cannot import name 'AttrsDescriptor' from 'triton.compiler.compiler' (C:\Portable\torch260\Lib\site-packages\triton\compiler\compiler.py)

2025-04-23T13:52:02.281576 - Prompt executed in 0.29 seconds

**Comment by lshqqytiger** [comment]
triton 3.3.0 is not fully compatible with torch 2.6.0.
Related: https://github.com/pytorch/pytorch/blob/7c97720d16b8dcc09bf0bdeefdbcbd84ab0ce9d6/torch/_inductor/runtime/hints.py#L82

**Comment by chain2k** [comment]
Which version of triton is better to use for compatibility with torch 2.6.0?

**Comment by lshqqytiger** [comment]
After 3.0.0 and before 3.3.0
3.0.0 is available in this release.
https://github.com/lshqqytiger/triton/releases/tag/2b248f14

**Comment by lshqqytiger** [comment]
PyTorch 2.7 is released. triton 3.3.0 should work fine with 2.7
https://github.com/pytorch/pytorch/releases/tag/v2.7.0
https://github.com/lshqqytiger/triton/releases/tag/37fd31dc

**Comment by chain2k** [comment]
Installed torch 2.7 and zluda 3.9.3. Got an error with triton 3.3.0. I'll be back home in May, I'll be able to write down which one. Installed triton 3.0.0, everything seems to work fine there, but there is a different error:
`triton.runtime.errors.OutOfResources: out of resource: shared memory, Required: 106496, Hardware limit: 65536. Reducing block sizes or num_stages may help.`
Does anyone know how to lower these values? Or I found this solution, is there any way to customize it?
[https://github.com/state-spaces/mamba/issues/387](https://github.com/state-spaces/mamba/issues/url)

**Comment by lshqqytiger** [comment]
Reducing shared memory requirements depends on your application.
If the application does only consider the newer NVIDIA architectures, reducing may not be possible.
It seems the kernel is optimized for NVIDIA Ampere and Ada Lovelace architectures, which have 128KB of shared memory per streaming multiprocessor.
However, AMD RDNA architecture has up to 64KB (65536 bytes) of shared memory per work group processor. (and 256KB per shader engine. the memory architecture is more layered than NVIDIA)
If possible, it works best with the triton kernels, which are optimized for AMDGPUs on Linux usage. (e.g. flash attention)

**Comment by sfinktah** [comment]
> However, AMD RDNA architecture has up to 64KB

Don't I know it, I've been fighting with sageattention all day about it.  But that's not why I write.

Triton 3.3 isn't really compatible with torch 2.7 at all.  But I have written some patches that force the two to get along, and they work really great now.  Though you definately need to set TRITON_OVERRIDE_ARCH=gfxxxx because it will forcefully override the detected environment (such as when ZLUDA is telling it that it's cuda).

https://github.com/sfinktah/amd-torch/tree/main/patches

Just the triton and the torch patches, ignore the sageattention patch or any other patches that may be there.
